In [1]:
import sys

In [2]:
print(sys.executable)

/home/simonque/Documents/code/env/bin/python3


In [3]:
print(sys.prefix)

/home/simonque/Documents/code/env


Steepest Descent
===================================

# Import Libraries

In [4]:
import numpy as np 
import matplotlib.pyplot as plt
import argparse
import csv

In [5]:
# parser = argparse.ArgumentParser(
#     description = "Perform regularized linear model regression from scratch.")
# parser.add_argument("filepath", type=str, help="Path to the input file")
# parser.add_argument("lambda_val", type=float, help="Lambda value used for LSE and Steepest Descent")
# parser.add_argument("num_polynomial_bases", type=int, help="Number of polynomial bases")
# args = parser.parse_args()

# Define input filename and parameters

In [6]:
filename = "input.txt"
lambda_val = 10000
num_polynomial_bases = 3

# Read the input file and store input data points into a list 

In [7]:
datapoints = []
with open(filename, 'r', encoding='utf-8') as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        datapoints.append([float(i) for i in row])
num_datapoints = len(datapoints)
print(f"number of datapoints: {num_datapoints}\n")

datapoints_arr = np.zeros((num_datapoints, 2), dtype=np.float64)

i = 0
for datapoint in datapoints:
    datapoints_arr[i,0] = datapoint[0]
    datapoints_arr[i,1] = datapoint[1]
    i+=1;

print(datapoints_arr)

number of datapoints: 23

[[-5.         51.76405235]
 [-4.79591837 45.42306433]
 [-4.59183673 41.2744481 ]
 [-3.97959184 26.6362165 ]
 [-3.57142857 20.25680606]
 [-2.95918367 11.61842924]
 [-2.75510204 10.45052507]
 [-1.73469388  1.84809823]
 [-1.32653061 -1.04053496]
 [-0.91836735 -4.6146308 ]
 [-0.71428571 -1.38719773]
 [-0.30612245 -1.9916444 ]
 [ 0.10204082 -0.91292461]
 [ 0.71428571  6.63482003]
 [ 1.12244898  9.54686746]
 [ 1.73469388 15.72016147]
 [ 1.93877551 20.62251684]
 [ 2.55102041 33.48059726]
 [ 2.95918367 40.76391966]
 [ 3.97959184 66.89976056]
 [ 4.3877551  78.44316466]
 [ 4.59183673 86.99156782]
 [ 5.         99.78725972]]


# Steepest Descent

## Create A and b

In [8]:
b = np.zeros((num_datapoints), dtype=np.float64)
b = datapoints_arr[:,1]
    
A = np.zeros((num_datapoints, num_polynomial_bases), dtype=np.float64)
for basis in range(num_polynomial_bases):
    A[:,basis] = datapoints_arr[:,0] ** basis


In [9]:
A

array([[ 1.00000000e+00, -5.00000000e+00,  2.50000000e+01],
       [ 1.00000000e+00, -4.79591837e+00,  2.30008330e+01],
       [ 1.00000000e+00, -4.59183673e+00,  2.10849646e+01],
       [ 1.00000000e+00, -3.97959184e+00,  1.58371512e+01],
       [ 1.00000000e+00, -3.57142857e+00,  1.27551020e+01],
       [ 1.00000000e+00, -2.95918367e+00,  8.75676801e+00],
       [ 1.00000000e+00, -2.75510204e+00,  7.59058726e+00],
       [ 1.00000000e+00, -1.73469388e+00,  3.00916285e+00],
       [ 1.00000000e+00, -1.32653061e+00,  1.75968347e+00],
       [ 1.00000000e+00, -9.18367347e-01,  8.43398584e-01],
       [ 1.00000000e+00, -7.14285714e-01,  5.10204082e-01],
       [ 1.00000000e+00, -3.06122449e-01,  9.37109538e-02],
       [ 1.00000000e+00,  1.02040816e-01,  1.04123282e-02],
       [ 1.00000000e+00,  7.14285714e-01,  5.10204082e-01],
       [ 1.00000000e+00,  1.12244898e+00,  1.25989171e+00],
       [ 1.00000000e+00,  1.73469388e+00,  3.00916285e+00],
       [ 1.00000000e+00,  1.93877551e+00

In [10]:
b

array([51.76405235, 45.42306433, 41.2744481 , 26.6362165 , 20.25680606,
       11.61842924, 10.45052507,  1.84809823, -1.04053496, -4.6146308 ,
       -1.38719773, -1.9916444 , -0.91292461,  6.63482003,  9.54686746,
       15.72016147, 20.62251684, 33.48059726, 40.76391966, 66.89976056,
       78.44316466, 86.99156782, 99.78725972])

## Define learning rate

In [11]:
learning_rate = 0.0001

## Initialize weights, biases

In [12]:
x = np.zeros(shape=num_polynomial_bases, dtype=np.float32)
# x = np.array([-0.2314002,  4.90619  ,  3.0238533])

## Define error function

In [13]:
def compute_error(A, x, b):
    Ax = np.dot(A, x)
    error = np.sum(np.abs(Ax - b) ** 2)
    return error

## Get the LSE gradient

In [14]:
A_t = np.transpose(A)

In [15]:
learning_rate = 1e-4

In [42]:
for i in range(500):
    x_t = np.transpose(x)
    grad = 2 * (np.dot(x_t, np.dot(A_t, A))-np.dot(A_t, b))
    # print(x)
    # print(grad)
    e = np.zeros(shape=x.shape)
    e[np.argmax(np.abs(grad))] = 1
    # print(e)
    grad = grad * e
    error = compute_error(A, x, b)
    print(f"Total error: {error}")
    x = x - learning_rate * grad
    

Total error: 26.55995949933475
Total error: 26.559959499334727
Total error: 26.559959499334727
Total error: 26.559959499334727
Total error: 26.5599594993347
Total error: 26.55995949933471
Total error: 26.559959499334713
Total error: 26.559959499334706
Total error: 26.5599594993347
Total error: 26.55995949933469
Total error: 26.559959499334695
Total error: 26.559959499334692
Total error: 26.559959499334635
Total error: 26.559959499334674
Total error: 26.559959499334653
Total error: 26.559959499334628
Total error: 26.559959499334628
Total error: 26.559959499334603
Total error: 26.55995949933464
Total error: 26.55995949933464
Total error: 26.55995949933462
Total error: 26.559959499334592
Total error: 26.559959499334585
Total error: 26.559959499334575
Total error: 26.559959499334614
Total error: 26.55995949933457
Total error: 26.55995949933458
Total error: 26.559959499334564
Total error: 26.55995949933457
Total error: 26.559959499334543
Total error: 26.559959499334553
Total error: 26.55995

In [43]:
x

array([-0.2314016 ,  4.90619026,  3.02385338])